
import { Category, Job, Review } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    category: Category.CLEANING,
    title: '성동구 옥수동 오피스텔 입주청소',
    location: '성동구 옥수동',
    price: 150000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean1/400/300',
    isPopular: true,
    tags: ['방1', '화장실1', '주방1', '거실1'],
    description: '한남/이태원 풀옵션 오피스텔 청소 전문가를 모십니다.',
    lat: 37.545,
    lng: 127.012,
    rating: 4.8,
    reviewCount: 124
  },
  {
    id: '2',
    category: Category.PET_WALKING,
    title: '상도동 골든리트리버 저녁 산책',
    location: '동작구 상도동',
    price: 25000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/dog1/400/300',
    isPopular: true,
    tags: ['대형견가능', '주말우대'],
    description: '성격 좋은 리트리버와 함께 산책하실 분!',
    lat: 37.502,
    lng: 126.947,
    rating: 4.9,
    reviewCount: 56
  },
  {
    id: '3',
    category: Category.MOVING,
    title: '서대문구 원룸 소형 용달 이사',
    location: '서대문구 북가좌동',
    price: 80000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/move1/400/300',
    tags: ['명지대 주차o', '깔끔원룸'],
    description: '간단한 짐 이동 도와주실 용달 기사님 구합니다.',
    lat: 37.581,
    lng: 126.911,
    rating: 4.7,
    reviewCount: 89
  },
  {
    id: '4',
    category: Category.CLEANING,
    title: '강남구 역삼동 투룸 거주청소',
    location: '강남구 역삼동',
    price: 215000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean2/400/300',
    tags: ['당일지급', '전문장비제공'],
    description: '이사 전 꼼꼼하게 청소해주실 분을 찾습니다.',
    lat: 37.498,
    lng: 127.027,
    rating: 5.0,
    reviewCount: 12
  },
  // --- 입주청소 10개 추가 ---
  {
    id: 'c1',
    category: Category.CLEANING,
    title: '마포구 공덕동 신축 아파트 입주청소',
    location: '마포구 공덕동',
    price: 320000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean3/400/300',
    tags: ['신축아파트', '창틀청소'],
    description: '공덕역 인근 신축 아파트 첫 입주 청소입니다.',
    lat: 37.543,
    lng: 126.951,
    rating: 4.9,
    reviewCount: 45
  },
  {
    id: 'c2',
    category: Category.CLEANING,
    title: '강서구 마곡동 오피스텔 원룸 청소',
    location: '강서구 마곡동',
    price: 120000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean4/400/300',
    tags: ['원룸', '자재주의'],
    description: '혼자 거주하는 원룸 깔끔하게 청소해주실 분.',
    lat: 37.560,
    lng: 126.825,
    rating: 4.6,
    reviewCount: 31
  },
  {
    id: 'c3',
    category: Category.CLEANING,
    title: '송파구 잠실동 빌라 이사 청소',
    location: '송파구 잠실동',
    price: 250000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean5/400/300',
    tags: ['빌라', '화장실집중'],
    description: '방3 화2 빌라입니다. 구석구석 부탁드려요.',
    lat: 37.506,
    lng: 127.084,
    rating: 4.7,
    reviewCount: 62
  },
  {
    id: 'c4',
    category: Category.CLEANING,
    title: '노원구 상계동 아파트 거주청소',
    location: '노원구 상계동',
    price: 280000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean6/400/300',
    tags: ['아파트', '주방기름때'],
    description: '주방 기름때 제거 위주로 부탁드립니다.',
    lat: 37.660,
    lng: 127.061,
    rating: 4.5,
    reviewCount: 28
  },
  {
    id: 'c5',
    category: Category.CLEANING,
    title: '용산구 이촌동 한강변 아파트 청소',
    location: '용산구 이촌동',
    price: 350000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean7/400/300',
    isPopular: true,
    tags: ['대형평수', '경력우대'],
    description: '청소 경력 3년 이상 전문가님 선호합니다.',
    lat: 37.521,
    lng: 126.973,
    rating: 4.9,
    reviewCount: 156
  },
  {
    id: 'c6',
    category: Category.CLEANING,
    title: '영등포구 당산동 복층 오피스텔',
    location: '영등포구 당산동',
    price: 180000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean8/400/300',
    tags: ['복층', '높은층고'],
    description: '복층 유리창 청소가 포함된 일정입니다.',
    lat: 37.534,
    lng: 126.896,
    rating: 4.8,
    reviewCount: 42
  },
  {
    id: 'c7',
    category: Category.CLEANING,
    title: '서초구 반포동 프리미엄 입주케어',
    location: '서초구 반포동',
    price: 450000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean9/400/300',
    tags: ['고가자재', '피톤치드'],
    description: '피톤치드 서비스 포함된 입주 청소입니다.',
    lat: 37.503,
    lng: 127.001,
    rating: 5.0,
    reviewCount: 88
  },
  {
    id: 'c8',
    category: Category.CLEANING,
    title: '은평구 불광동 신축빌라 청소',
    location: '은평구 불광동',
    price: 160000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean10/400/300',
    tags: ['가성비', '오전시작'],
    description: '오전에 빠르게 마무리해주실 분 찾아요.',
    lat: 37.610,
    lng: 126.929,
    rating: 4.4,
    reviewCount: 15
  },
  {
    id: 'c9',
    category: Category.CLEANING,
    title: '강동구 천호동 다가구 주택 청소',
    location: '강동구 천호동',
    price: 190000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean11/400/300',
    tags: ['구옥청소', '꼼꼼함'],
    description: '오래된 주택이라 꼼꼼한 청소가 필요합니다.',
    lat: 37.538,
    lng: 127.123,
    rating: 4.7,
    reviewCount: 53
  },
  {
    id: 'c10',
    category: Category.CLEANING,
    title: '관악구 신림동 원룸 퇴거청소',
    location: '관악구 신림동',
    price: 100000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/clean12/400/300',
    tags: ['당일지급', '간단청소'],
    description: '방 뺀 후 다음 세입자 들어오기 전 청소.',
    lat: 37.484,
    lng: 126.930,
    rating: 4.3,
    reviewCount: 110
  },

  // --- 애완동물 산책 10개 추가 ---
  {
    id: 'p1',
    category: Category.PET_WALKING,
    title: '용산구 한남동 푸들 산책 파트너',
    location: '용산구 한남동',
    price: 18000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet1/400/300',
    tags: ['소형견', '매너좋음'],
    description: '착한 푸들 초코와 함께 1시간 산책해요.',
    lat: 37.531,
    lng: 127.006,
    rating: 4.9,
    reviewCount: 23
  },
  {
    id: 'p2',
    category: Category.PET_WALKING,
    title: '마포구 연남동 시바견 산책',
    location: '마포구 연남동',
    price: 22000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet2/400/300',
    tags: ['활동적', '연트럴파크'],
    description: '연남동 경의선 숲길 산책하실 분 구합니다.',
    lat: 37.561,
    lng: 126.924,
    rating: 4.8,
    reviewCount: 37
  },
  {
    id: 'p3',
    category: Category.PET_WALKING,
    title: '강남구 압구정동 비숑 프리제 산책',
    location: '강남구 압구정동',
    price: 30000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet3/400/300',
    tags: ['매너교육완료', '도산공원'],
    description: '매너 교육이 잘 된 비숑입니다. 조심히 부탁드려요.',
    lat: 37.527,
    lng: 127.036,
    rating: 5.0,
    reviewCount: 14
  },
  {
    id: 'p4',
    category: Category.PET_WALKING,
    title: '성동구 성수동 진돗개 오전 산책',
    location: '성동구 성수동',
    price: 25000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet4/400/300',
    tags: ['중형견', '서울숲'],
    description: '서울숲에서 아침 운동 겸 산책해요.',
    lat: 37.544,
    lng: 127.044,
    rating: 4.7,
    reviewCount: 41
  },
  {
    id: 'p5',
    category: Category.PET_WALKING,
    title: '종로구 삼청동 웰시코기 산책',
    location: '종로구 삼청동',
    price: 20000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet5/400/300',
    tags: ['호기심많음', '한옥마을'],
    description: '한옥마을 골목길 산책을 좋아하는 코기입니다.',
    lat: 37.582,
    lng: 126.981,
    rating: 4.9,
    reviewCount: 19
  },
  {
    id: 'p6',
    category: Category.PET_WALKING,
    title: '광진구 자양동 대형견 도베르만',
    location: '광진구 자양동',
    price: 40000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet6/400/300',
    tags: ['대형견숙련자', '힘좋음'],
    description: '도베르만 산책 경험 있으신 분만 지원 부탁드립니다.',
    lat: 37.532,
    lng: 127.069,
    rating: 5.0,
    reviewCount: 8
  },
  {
    id: 'p7',
    category: Category.PET_WALKING,
    title: '송파구 문정동 몰티즈 오후 산책',
    location: '송파구 문정동',
    price: 15000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet7/400/300',
    tags: ['노령견', '천천히산책'],
    description: '나이가 많은 몰티즈라 아주 천천히 걸어주셔야 해요.',
    lat: 37.486,
    lng: 127.121,
    rating: 4.6,
    reviewCount: 65
  },
  {
    id: 'p8',
    category: Category.PET_WALKING,
    title: '양천구 목동 보더콜리 활동지원',
    location: '양천구 목동',
    price: 28000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet8/400/300',
    tags: ['터그놀이', '에너지폭발'],
    description: '공놀이와 산책을 병행해주실 에너지 넘치는 분!',
    lat: 37.537,
    lng: 126.874,
    rating: 4.9,
    reviewCount: 22
  },
  {
    id: 'p9',
    category: Category.PET_WALKING,
    title: '중구 명동 포메라니안 주말 산책',
    location: '중구 명동',
    price: 20000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet9/400/300',
    tags: ['애교쟁이', '사진촬영필수'],
    description: '산책 중 예쁜 사진 한 장 부탁드려요.',
    lat: 37.563,
    lng: 126.984,
    rating: 4.8,
    reviewCount: 30
  },
  {
    id: 'p10',
    category: Category.PET_WALKING,
    title: '강동구 고덕동 래브라도 주말 산책',
    location: '강동구 고덕동',
    price: 35000,
    priceUnit: '시간',
    imageUrl: 'https://picsum.photos/seed/pet10/400/300',
    tags: ['순둥이', '물놀이좋아함'],
    description: '근처 공원에서 물놀이도 가능한 래브라도입니다.',
    lat: 37.554,
    lng: 127.155,
    rating: 4.9,
    reviewCount: 12
  },

  // --- 용달 이사 10개 추가 ---
  {
    id: 'm1',
    category: Category.MOVING,
    title: '관악구 봉천동 소형 원룸 이사',
    location: '관악구 봉천동',
    price: 60000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving1/400/300',
    tags: ['짐적음', '엘리베이터O'],
    description: '박스 10개 정도의 아주 가벼운 이사입니다.',
    lat: 37.481,
    lng: 126.953,
    rating: 4.7,
    reviewCount: 204
  },
  {
    id: 'm2',
    category: Category.MOVING,
    title: '동대문구 회기동 대학생 자취 이사',
    location: '동대문구 회기동',
    price: 55000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving2/400/300',
    tags: ['대학가', '학생할인문의'],
    description: '경희대 인근 원룸 이사 도와주실 분.',
    lat: 37.589,
    lng: 127.057,
    rating: 4.5,
    reviewCount: 142
  },
  {
    id: 'm3',
    category: Category.MOVING,
    title: '동작구 흑석동 소형 가전 이동',
    location: '동작구 흑석동',
    price: 40000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving3/400/300',
    tags: ['세탁기한대', '당일가능'],
    description: '중고거래한 세탁기 한 대만 옮겨주시면 됩니다.',
    lat: 37.509,
    lng: 126.963,
    rating: 4.8,
    reviewCount: 56
  },
  {
    id: 'm4',
    category: Category.MOVING,
    title: '노원구 중계동 학생 가구 운반',
    location: '노원구 중계동',
    price: 70000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving4/400/300',
    tags: ['책상운반', '2인가능'],
    description: '무거운 책상이 하나 있어서 같이 들어주셔야 합니다.',
    lat: 37.649,
    lng: 127.076,
    rating: 4.6,
    reviewCount: 38
  },
  {
    id: 'm5',
    category: Category.MOVING,
    title: '중구 황학동 가구 배송 및 설치',
    location: '중구 황학동',
    price: 120000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving5/400/300',
    tags: ['설치포함', '침대프레임'],
    description: '이케아 침대 운반 및 조립까지 도와주실 전문가.',
    lat: 37.568,
    lng: 127.020,
    rating: 4.9,
    reviewCount: 77
  },
  {
    id: 'm6',
    category: Category.MOVING,
    title: '금천구 가산동 사무실 소형 이전',
    location: '금천구 가산동',
    price: 150000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving6/400/300',
    tags: ['기업우대', '계산서가능'],
    description: '작은 사무실 집기 이동입니다. 야간 작업 가능하신 분.',
    lat: 37.481,
    lng: 126.883,
    rating: 4.7,
    reviewCount: 29
  },
  {
    id: 'm7',
    category: Category.MOVING,
    title: '성북구 안암동 소형 가전 단거리 이동',
    location: '성북구 안암동',
    price: 35000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving7/400/300',
    tags: ['근거리', '가벼운짐'],
    description: '안암동 내에서 500m 거리 이동입니다.',
    lat: 37.586,
    lng: 127.029,
    rating: 4.4,
    reviewCount: 92
  },
  {
    id: 'm8',
    category: Category.MOVING,
    title: '도봉구 창동 아파트 원룸 이사',
    location: '도봉구 창동',
    price: 90000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving8/400/300',
    tags: ['사다리차불필요', '주차가능'],
    description: '짐이 많지 않은 1.5룸 이사입니다.',
    lat: 37.653,
    lng: 127.047,
    rating: 4.8,
    reviewCount: 64
  },
  {
    id: 'm9',
    category: Category.MOVING,
    title: '강북구 수유동 야간 용달 호출',
    location: '강북구 수유동',
    price: 110000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving9/400/300',
    tags: ['야간작업', '긴급'],
    description: '급하게 밤에 짐을 옮겨야 합니다. 연락 주세요.',
    lat: 37.637,
    lng: 127.025,
    rating: 4.2,
    reviewCount: 18
  },
  {
    id: 'm10',
    category: Category.MOVING,
    title: '강동구 성내동 원룸 풀서비스 이사',
    location: '강동구 성내동',
    price: 200000,
    priceUnit: '건',
    imageUrl: 'https://picsum.photos/seed/moving10/400/300',
    tags: ['포장이사지원', '전문가'],
    description: '소형 포장 이사 서비스입니다. 몸만 오셔도 돼요.',
    lat: 37.528,
    lng: 127.129,
    rating: 5.0,
    reviewCount: 312
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    author: '김*현',
    rating: 5,
    content: '청소가 너무 깔끔해요. 덕분에 기분 좋게 입주했습니다.',
    location: '제주특별자치도 제주시',
    jobTitle: '침대(3/6인) 2층집 청소',
    imageUrl: 'https://picsum.photos/seed/rev1/400/300'
  },
  {
    id: 'r2',
    author: '이*준',
    rating: 5,
    content: '강아지가 너무 좋아하네요. 다음에도 꼭 부탁드리고 싶어요.',
    location: '서울 강북구 미아동',
    jobTitle: '대형견 산책 서비스',
    imageUrl: 'https://picsum.photos/seed/rev2/400/300'
  },
  {
    id: 'r3',
    author: '박*서',
    rating: 4,
    content: '친절하시고 짐도 조심히 옮겨주셨습니다. 만족해요!',
    location: '부산 해운대구',
    jobTitle: '원룸 용달 이사',
    imageUrl: 'https://picsum.photos/seed/rev3/400/300'
  }
];
